MockTask/Controllers/ClassesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MockTask.DBContext;
using MockTask.Models;
using MockTask.Services;

namespace MockTask.Controllers
{
    public class ClassesController : Controller
    {
        private readonly ApplicationDBContext _context;
        private readonly SQLService _sqlService;

        public ClassesController(ApplicationDBContext context, SQLService sqlService)
        {
            _sqlService = sqlService;
            _context = context;
            
        }

        public IActionResult Index()
        {
            return View(_sqlService.GetAll(new Classes()));
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Classes classes)
        {
            if (ModelState.IsValid)
            {
                _context.Add(classes);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(classes);
        }


        private bool ClassesExists(int id)
        {
            return _context.Classes.Any(e => e.Id == id);
        }
    }
}

MockTask/Views/Classes/Create.cshtml
@model MockTask.Models.Classes

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Classes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Classes">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="submit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MockTask/Views/Classes/Index.cshtml
@model IEnumerable<MockTask.Models.Classes>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Number)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Number)
            </td>
        </tr>
}
    </tbody>
</table>
<div>
    <a href="~/">Back to home page</a>
</div>